import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UserProvider from "@/contexts/UserProvider";
import { SocketProvider } from "@/contexts/SocketProvider";
import { TransactionProvider } from "@/contexts/TransactionProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Expense Tracking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <TransactionProvider>
        <SocketProvider>
          <html lang="en">
            <body className={inter.className}>
              {children}
              <Toaster />
            </body>
          </html>
        </SocketProvider>
      </TransactionProvider>
    </UserProvider>
  );
}
